### ISSUE TITLE
Maliput Viewer - RoadGeometry properties

### ISSUE THREAD

**Issue by agalbachicar** [maliput/delphyne_gui#113]
To improve the introspection capabilities of this application, it is desired to get RoadGeometry properties from the 3D scene. Those properties would be:

- Lane / Segment / Junction IDs.
- World coordinates.
- Lane coordinates.

The user will move the scene to visualize different sections of the RoadGoemetry. Then, if he clicks over the RoadGeometry, previously named information fields will be filled with the respective information.

**Questions:**

- Are those parameters enough?
- Do we want to also select branch points?

**Technical details:**

To get the 3D points from the 2D canvas, here are some useful links:
- https://bitbucket.org/ignitionrobotics/ign-rendering/src/446f37de18c6/examples/mouse_picking/GlutWindow.cc
- https://bitbucket.org/ignitionrobotics/ign-rendering/src/default/include/ignition/rendering/RayQuery.hh
- https://bitbucket.org/ignitionrobotics/ign-rendering/src/default/ogre/src/OgreRayQuery.cc

To get the RoadGeometry from a 3D point, querying `RoadGeometry::DoToRoadPosition()` will be necessary.

**Comment by francocipollone** [comment]
This is already implemented
